defmodule Tradehub.Model.Market do
  @derive Jason.Encoder
  defstruct [
    :base,
    :base_name,
    :base_precision,
    :closed_block_height,
    :created_block_height,
    :description,
    :display_name,
    :expiry_time,
    :impact_size,
    :index_oracle_id,
    :initial_margin_base,
    :initial_margin_step,
    :is_active,
    :is_settled,
    :last_price_protected_band,
    :lot_size,
    :maintenance_margin_ratio,
    :maker_fee,
    :mark_price_band,
    :market_type,
    :max_liquidation_order_duration,
    :max_liquidation_order_ticket,
    :min_quantity,
    :name,
    :quote,
    :quote_name,
    :quote_precision,
    :risk_step_size,
    :taker_fee,
    :tick_size,
    :type
  ]
end
